Cinema/Areas/Adminisration/Controllers/ProjectionsController.cs
using Cinema.Core.Contracts;
using Cinema.Core.Models.Projection;
using Microsoft.AspNetCore.Mvc;

namespace Cinema.Areas.Adminisration.Controllers
{
    public class ProjectionsController : Controller
    {
        private readonly IProjectionService projectionService;

        public ProjectionsController(IProjectionService _projectionService)
        {
            projectionService = _projectionService;
        }

        public async Task<IActionResult> Details(int projectionId)
        {
            var model = await projectionService.GetProjectionDetails(projectionId);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AllProjection()
        {
            var model = await projectionService.GetAllProjectionAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddProjection()
        {
            var model = new AddProjectionViewModel()
            {
                Halls = await projectionService.GetHallAsync(),
                Movies = await projectionService.GetAllMoviesAsync()

            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddProjection(AddProjectionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Movies = await projectionService.GetAllMoviesAsync();
                model.Halls = await projectionService.GetHallAsync();
                return View(model);
            }

            try
            {
                await projectionService.AddProjectionAsync(model);

                return RedirectToAction("All", "Movies");
            }
            catch (Exception)
            {

                ModelState.AddModelError("", "Something went wrong");

                model.Movies = await projectionService.GetAllMoviesAsync();
                model.Halls = await projectionService.GetHallAsync();
                return View(model);

            }
        }
    }
}

Cinema/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cinema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cinema.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cinema</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="All">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projections" asp-action="AllProjection">Projections</a>
                        </li>
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administration" asp-controller="Movies" asp-action="Add">Add</a>
                            </li>
                        }
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administration" asp-controller="Projections" asp-action="AddProjection">Add Projection</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - Cinema
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>